### ISSUE TITLE
Get "Undefined Error" when adding F5 Cluster to the F5 Service Center App

### ISSUE THREAD

**Issue by kennguyen3085** [F5Networks/f5-aci-servicecenter#133]
Hello,

We tried to add the first F5 cluster to the app but kept getting error "Undefined Error". Tried adding using both IP & DNS Name, tried different browsers Chrome and Firefox, ACI and F5's credential are admin account... still getting the same error. The F5 Service Center shows no faults. Could our current ACI license status "Out of  compliance" be the problem? 

Best,

Ken

**Comment by selinaarokiaswamy-GSLAB** [comment]
Hi Ken, could you please provide more clarity on this issue? Snapshots would be helpful.

**Comment by kennguyen3085** [comment]
<img width="774" alt="Capture" src="https://github.com/F5Networks/f5-aci-servicecenter/assets/62999806/23c2c09c-f4b4-4666-84d4-060fcf678056">
Hello,
Please see the attached screenshot for the error. F5 version is 15.1.2
My ACI version is 4.2(7u), ServiceCenter app's version is 2.11.2
<img width="225" alt="ServiceCenter Version" src="https://github.com/F5Networks/f5-aci-servicecenter/assets/62999806/26c50fb2-3575-4489-97e3-25528c5f5b6e">
F5 is a cluster of 2 physical and 2 virtual. ACI has no F5 related faults except a "Out of Compliance" license issue that we are working with TAC to resolve.

Best,

Ken

**Comment by jyeung-F5** [comment]
Hi Ken,

"Undefined Error" indicates a backend issue.  Disabling then re-enabling the app will usually fix the issue as it will restart the backend, which is also the first step in troubleshooting.  Since v2.11.3 is now available, can you please uninstall v2.11.2 and install v2.11.3 instead of disabling/enabling the app?  Also, it will be great if you can make the F5 account team aware of the usage of F5 ACI ServiceCenter.  Please let us know how it goes and if you have further questions.  Thanks!

Regards,
Jennifer

**Comment by kennguyen3085** [comment]
Hi Jennifer

I tried disabling and re-enabling v2.11.2; also uninstalled it and installed v2.11.3 still same error. Do you know if there is anything else we can try?

Best,

Ken

**Comment by jyeung-F5** [comment]
Hi Ken,

If that does not resolve the issue, we will need to find out what’s going on with the backend service on the APIC.  Can you please take a screenshot of the App Faults tab on the APIC and send it to f5_aci_app_support@f5.com so that we can further assist you from there?  Thanks!

Regards,
Jennifer

**Comment by kennguyen3085** [comment]
Hi Jennefer,

First, thank you for looking into this. I have sent couple emails with the screenshot to f5_aci_app_support@f5.com. One of the emails could not be delivered. Did you receive them?

This is a production network and I believe we have a support contract with F5. Would you like us to call F5 TAC and open a case through them as well?

Best,

Ken

**Comment by jyeung-F5** [comment]
Hi Ken, 

I just checked with the Support and they should have re-sent the response to you again.  Thanks!

Regards,
Jennifer

**Comment by jyeung-F5** [comment]
The issue was due to APIC sync issue and customer will further investigate with Cisco. Closing out this ticket.
